### ISSUE TITLE
Building book fails

### ISSUE THREAD

**Issue by deepankarsharma** [leanprover/fp-lean#176]
The error I get when I change directory into functional-programming-lean and run "mdbook build"

```text
[dman@zen5 functional-programming-lean]$ mdbook build 
2024-12-01 10:09:33 [INFO] (mdbook::book): Book building has started
Output:
b'/bin/sh: line 1: ./run: cannot execute: required file not found\n'
Stderr:
None
Traceback (most recent call last):
  File "/home/dman/tinkering/lean/fp-lean/functional-programming-lean/scripts/projects.py", line 157, in <module>
    main()
  File "/home/dman/tinkering/lean/fp-lean/functional-programming-lean/scripts/projects.py", line 154, in main
    print(json.dumps(ctx.run_examples(context, book_contents)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dman/tinkering/lean/fp-lean/functional-programming-lean/scripts/projects.py", line 145, in run_examples
    test_chapters(book['sections'])
  File "/home/dman/tinkering/lean/fp-lean/functional-programming-lean/scripts/projects.py", line 143, in test_chapters
    test_chapters(ch['Chapter']['sub_items'])
  File "/home/dman/tinkering/lean/fp-lean/functional-programming-lean/scripts/projects.py", line 140, in test_chapters
    ch['Chapter']['content'] = command_re.sub(self.rewrite_command(project_root), ch['Chapter']['content'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dman/tinkering/lean/fp-lean/functional-programming-lean/scripts/projects.py", line 89, in rewrite
    raise e
  File "/home/dman/tinkering/lean/fp-lean/functional-programming-lean/scripts/projects.py", line 76, in rewrite
    val = subprocess.run(command,
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './run' returned non-zero exit status 127.
2024-12-01 10:09:34 [ERROR] (mdbook::utils): Error: The "commands" preprocessor exited unsuccessfully with exit status: 1 status
```

My version of lean 

```text
[dman@zen5 functional-programming-lean]$ elan show 
installed toolchains
--------------------

leanprover-community/lean:3.23.0
leanprover/lean4:4.1.0
leanprover/lean4:stable
leanprover/lean4:v4.13.0-rc3
leanprover/lean4:v4.7.0
4.1.0 (default)

active toolchain
----------------

4.1.0 (default)
Lean (version 4.1.0, commit a832f398b80a, Release)
```

My version of Python
```text
[dman@zen5 functional-programming-lean]$ python --version
Python 3.12.7
```

My OS (Archlinux)
```text
[dman@zen5 functional-programming-lean]$ uname -a 
Linux zen5 6.11.0-g2f27fce67173 #1 SMP PREEMPT_DYNAMIC Tue Sep 17 20:53:22 EDT 2024 x86_64 GNU/Linux
```

Version of mdbook 
```text
[dman@zen5 functional-programming-lean]$ mdbook --version
mdbook v0.4.43
```

**Comment by david-christiansen** [comment]
When I next get a chance to work on the book, I'll see if I can replicate this.

In case you're wanting to poke at it in the meantime, this looks like one of the scripts that checks the examples in the book. They create a temporary directory, put some files in it, and then execute a shell script called "run". Perhaps there's some missing error handling, or your `/tmp` isn't allowing an executable bit to be set?

**Comment by deepankarsharma** [comment]
I was able to triage this and it was an error on my part. I was missing expect on my machine.

**Comment by david-christiansen** [comment]
Thanks for following up!
